[features]
seeds = false

[programs.devnet]
tiktok_clone = "4AgStVZD26kU6q75igrLHCJQbh4NKt2RggWYWts3j78r"

[programs.localnet]
tiktok_clone = "7hK31f2WnAeGeFkwNRfNCiKW1bx2PhaTB3jK719r7CXf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
#cluster = "localnet"

wallet = "/home/duyman/.config/solana/id.json"

[workspace]
types = "../frontend/utils/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/start.ts"
